server:
  port: 8080

spring:
  application:
    name: life-os-server

  datasource:
    url: jdbc:mysql://localhost:3306/mobe?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  Jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: info